name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

trigger:
- master

resources:
- repo: self

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Chartmuseum
  - name: tag
    value: '$(Build.BuildId)'

steps:

  - task: HelmInstaller@0
    displayName: 'Install Helm 3.2.4'
    inputs:
      helmVersion: '3.2.4'
      checkLatestHelmVersion: false
      installKubectl: false

  - task: Bash@3
    displayName: 'Package charts'
    inputs:
      targetType: 'inline'
      script: |
        for d in */
        do 
          helm package ./$d
        done

  - task: Bash@3
    displayName: 'Upload to chart museum'
    inputs:
      targetType: 'inline'
      script: |
        for f in *.tgz
        do 
          echo "Uploading @$f"
          curl --data-binary "@$f" https://charts.sf9.io/api/charts --user $(User):$(Password)
        done   

  


