name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

trigger:
- master

resources:
- repo: self

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Chartmuseum
  - name: tag
    value: '$(Build.BuildId)'

steps:

  - task: HelmInstaller@0
    displayName: 'Install Helm 3.2.4'
    inputs:
      helmVersion: '3.2.4'
      checkLatestHelmVersion: false
      installKubectl: false

  


