{{- define "swlib.secret.tpl" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "project.fullname" . }}
data:

  {{- if .Values.db }}
  db: {{ .Values.db | b64enc }} 
  {{- end }}

  {{- if .Values.global.token.key }}
  tokenKey: {{ .Values.global.token.key | b64enc }} 
  {{- end }}

  {{- if .Values.global.token.issuer }}
  tokenIssuer: {{ .Values.global.token.issuer | b64enc }} 
  {{- end }}

  {{- if .Values.global.token.audience }}
  tokenAudience: {{ .Values.global.token.audience | b64enc }} 
  {{- end }}

  {{- if .Values.global.logger.esUrl }}
  esUrl: {{ .Values.global.logger.esUrl | b64enc }}
  {{- end }}

  {{- if .Values.global.logger.esUser }}
  esUser: {{ .Values.global.logger.esUser | b64enc }}
  {{- end }}

  {{- if .Values.global.logger.esPassword }}
  esPassword: {{ .Values.global.logger.esPassword | b64enc }}
  {{- end }}

  {{- if .Values.global.bus.rabbitUrl }}
  busRabbitUrl: {{ .Values.global.bus.rabbitUrl | b64enc }}
  {{- end }}

  {{- $root := . }}
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end -}}

{{- define "swlib.secret" -}}
{{- include "swlib.util.merge" (append . "swlib.secret.tpl") -}}
{{- end -}}

